name: hw2
root: .
startup_window: ros

windows:
  - ros:
      layout: 01b7,205x57,0,0{102x57,0,0[102x28,0,0{51x28,0,0,0,50x28,52,0,2},102x28,0,29,3],102x57,103,0[102x14,103,0,4,102x13,103,15,8,102x28,103,29,6]}
      panes:
        - roscore
        - vrep:
          - until rostopic list ; do sleep 1; done
          - clear
          - vrep -s $VREP_SCENES/rosControlKinect.ttt
        - rostopic:
          - until rostopic info /vrep/info; do sleep 1; done
          - clear
          - rostopic list
        - rosrun joy joy_node
        - 
  - vim:
      vim -O floor_plane_ceres/src/floor_plane_regression.cpp floor_plane_regression/src/floor_plane_regression.cpp
  - build:
      layout: even-horizontal
      panes:
        - build:
          - cd ~/ros_ws/
          - clear
        - git:
          - cd ..
          - clear
