name: p1
root: .
startup_window: ros
windows:
  - ros:
      layout: 2a7e,205x57,0,0{102x57,0,0[102x28,0,0{51x28,0,0,2,50x28,52,0,5},102x28,0,29,4],102x57,103,0,3}]
      panes:
        - roscore
        - vrep:
          - until rostopic list ; do sleep 1; done
          - clear
          - vrep -h -s ../scenes/lakeExample.ttt
        - rviz:
          - until rostopic info /vrep/info; do sleep 1; done
          - clear
          # - rosrun rviz rviz -d p1.rviz
        - rosrun rviz rviz
  - vim:
      vim -O shore_follower/src/shore_follower_drive.cpp
  - build:
      layout: even-horizontal
      panes:
        - build:
          - cd ~/ros_ws/
          - clear
        - git:
          - cd ..
          - clear
