name: p3
root: .
startup_window: ros
windows:
  - ros:
      layout: caaa,204x55,0,0{101x55,0,0[101x27,0,0{64x27,0,0,0,36x27,65,0,3},101x27,0,28,4],102x55,102,0[102x27,102,0,5,102x27,102,28{51x27,102,28,6,50x27,154,28,8}]}
      panes:
        - roscore
        - vrep:
          - until rostopic list ; do sleep 1; done
          - clear
          - vrep -s $VREP_SCENES/lakeExampleDrone.ttt
        - rviz:
          - until rostopic info /vrep/info; do sleep 1; done
          - clear
          - rosrun rviz rviz -d p3.rviz
        - roslaunch:
          - until rostopic info /vrep/info; do sleep 1; done
          - sleep 10
          - clear
          - roslaunch vrep_vsv_driver vsv_auto.launch
        - distance:
          - until rosnode info /shore_setpoint; do sleep 1; done
          - clear
          - rostopic pub -r1 /arm_ik/position geometry_msgs/Point "2.0" "0.0" "1.0"
          # - rosrun vrep_vsv_driver twist_arm.py
        - twist:
          - until rosnode info /shore_controller; do sleep 1; done
          - clear
          # - rosrun vrep_vsv_driver twist_robot.py
  - vim:
      vim -O vrep_vsv_driver/nodes/twist_robot.py vrep_vsv_driver/nodes/twist_arm.py
  - build:
      layout: even-horizontal
      panes:
        - build:
          - cd ~/ros_ws/
          - clear
        - git:
          - cd ..
          - clear
